apiVersion: v1
kind: Service
metadata:
  name: {{ include "cos-sftp.fullname" . }}
  labels:
    {{- include "cos-sftp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sftp
      protocol: TCP
      name: sftp
  selector:
    {{- include "cos-sftp.selectorLabels" . | nindent 4 }}
